// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeConcept.Models;

namespace TreeConcept.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191029082525_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TreeConcept.Models.Node", b =>
                {
                    b.Property<int>("AutoIncrement")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("Parent_ID");

                    b.HasKey("AutoIncrement");

                    b.ToTable("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
